  '/{version})/institutions/':
    get:
      description: >-
        Paginated list of verified Institutions affiliated with COS


        ##Institution Attributes


        OSF Institutions have the "institutions" `type`.


        name           type               description

        =========================================================================

        name           string             title of the institution

        id             string             unique identifier in the OSF

        logo_path      string             a path to the institution's static
        logo


        #This Request/Response
      parameters:
        - description: ''
          required: true
          type: string
          name: version
          in: path
        - description: ''
          required: false
          type: string
          name: page
          in: query
        - description: ''
          required: false
          type: string
          name: sort
          in: query
      tags:
        - institutions
      summary: Paginated list of verified Institutions affiliated with COS
      operationId: institutions_list
      responses:
        '200':
          description: ''
  '/{version})/institutions/auth/':
    post:
      tags:
        - institutions
      responses:
        '201':
          description: ''
      parameters:
        - description: ''
          required: true
          type: string
          name: version
          in: path
      operationId: institutions_auth_create
  '/{version})/institutions/{institution_id}/':
    get:
      description: >-
        Details about a given institution.


        ##Attributes


        OSF Institutions have the "institutions" `type`.


        name           type               description

        =========================================================================

        name           string             title of the institution

        id             string             unique identifier in the OSF

        logo_path      string             a path to the institution's static
        logo


        ##Relationships


        ###Nodes

        List of nodes that have this institution as its primary institution.


        ###Users

        List of users that are affiliated with this institution.


        ##Links
      parameters:
        - description: ''
          required: true
          type: string
          name: institution_id
          in: path
        - description: ''
          required: true
          type: string
          name: version
          in: path
      tags:
        - institutions
      summary: Details about a given institution.
      operationId: institutions_read
      responses:
        '200':
          description: ''
  '/{version})/institutions/{institution_id}/nodes/':
    get:
      description: |-
        Nodes that have selected an institution as their primary institution.

        ##Permissions
        Only public nodes or ones in which current user is a contributor.
      parameters:
        - description: ''
          required: true
          type: string
          name: institution_id
          in: path
        - description: ''
          required: true
          type: string
          name: version
          in: path
        - description: ''
          required: false
          type: string
          name: page
          in: query
        - description: ''
          required: false
          type: string
          name: 'page[size]'
          in: query
        - description: ''
          required: false
          type: string
          name: sort
          in: query
      tags:
        - institutions
      summary: Nodes that have selected an institution as their primary institution.
      operationId: institutions_nodes_list
      responses:
        '200':
          description: ''
  '/{version})/institutions/{institution_id}/registrations/':
    get:
      description: Registrations have selected an institution as their primary institution.
      parameters:
        - description: ''
          required: true
          type: string
          name: institution_id
          in: path
        - description: ''
          required: true
          type: string
          name: version
          in: path
        - description: ''
          required: false
          type: string
          name: page
          in: query
        - description: ''
          required: false
          type: string
          name: 'page[size]'
          in: query
        - description: ''
          required: false
          type: string
          name: sort
          in: query
      tags:
        - institutions
      summary: Registrations have selected an institution as their primary institution.
      operationId: institutions_registrations_list
      responses:
        '200':
          description: ''
  '/{version})/institutions/{institution_id}/relationships/nodes/':
    get:
      description: >-
        Relationship Endpoint for Institution -> Nodes Relationship


        Used to set, remove, update and retrieve the affiliated_institution of
        nodes with this institution


        ##Actions


        ###Create
      parameters:
        - description: ''
          required: true
          type: string
          name: institution_id
          in: path
        - description: ''
          required: true
          type: string
          name: version
          in: path
        - description: ''
          required: false
          type: string
          name: page
          in: query
        - description: ''
          required: false
          type: string
          name: 'page[size]'
          in: query
        - description: ''
          required: false
          type: string
          name: sort
          in: query
      tags:
        - institutions
      summary: Relationship Endpoint for Institution -> Nodes Relationship
      operationId: institutions_relationships_nodes_list
      responses:
        '200':
          description: ''
    post:
      description: >-
        Relationship Endpoint for Institution -> Nodes Relationship


        Used to set, remove, update and retrieve the affiliated_institution of
        nodes with this institution


        ##Actions


        ###Create
      parameters:
        - description: ''
          required: true
          type: string
          name: institution_id
          in: path
        - description: ''
          required: true
          type: string
          name: version
          in: path
        - schema:
            required:
              - data
            type: object
            properties:
              data:
                type: string
                description: ''
          name: data
          in: body
      tags:
        - institutions
      summary: Relationship Endpoint for Institution -> Nodes Relationship
      operationId: institutions_relationships_nodes_create
      consumes:
        - application/json
      responses:
        '201':
          description: ''
    delete:
      description: >-
        Relationship Endpoint for Institution -> Nodes Relationship


        Used to set, remove, update and retrieve the affiliated_institution of
        nodes with this institution


        ##Actions


        ###Create
      parameters:
        - description: ''
          required: true
          type: string
          name: institution_id
          in: path
        - description: ''
          required: true
          type: string
          name: version
          in: path
      tags:
        - institutions
      summary: Relationship Endpoint for Institution -> Nodes Relationship
      operationId: institutions_relationships_nodes_delete
      responses:
        '204':
          description: ''
  '/{version})/institutions/{institution_id}/users/':
    get:
      description: Users that have been authenticated with the institution.
      parameters:
        - description: ''
          required: true
          type: string
          name: institution_id
          in: path
        - description: ''
          required: true
          type: string
          name: version
          in: path
        - description: ''
          required: false
          type: string
          name: page
          in: query
        - description: ''
          required: false
          type: string
          name: 'page[size]'
          in: query
        - description: ''
          required: false
          type: string
          name: sort
          in: query
      tags:
        - institutions
      summary: Users that have been authenticated with the institution.
      operationId: institutions_users_list
      responses:
        '200':
          description: ''
